---
- name: "Creates backend directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy compiled backend"
  copy:
    src: dist.zip
    dest: "~/backend/dist.zip"

- name: "Unzip backend files to EC2 Instance"
  shell: |
    cd ~/backend
    unzip dist.zip
    rm -rf dist.zip

- name: "Install dependencies for project"
  shell: |
    cd ~/backend
    npm install

- name: "Executing node"
  shell: |
    export
    cd ~/backend
    pm2 start main.js
  register: execute_node

- name: print output message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
